project:
  type: book
  output-dir: docs

book:
  title: "Psychological data analysis for graduate students: *PSYC411*"
  author: 
    name: "Rob Davies"
    affiliation: "Department of Psychology, Lancaster University"
    email: r.davies1@lancaster.ac.uk
  date: "2024-11-05"
  chapters:
    - index.qmd
    - part: "DATA ANALYSIS"
    - hypotheses-associations.qmd
    - visualization-intro.qmd
    - visualization.qmd
    - lm-intro.qmd
    - lm-dev.qmd
    - part: "THE RESEARCH REPORT ASSIGNMENT"
    - report-preface.qmd
    - how.qmd
    - intro.qmd
    - part: "MAKING THE MOST OF R"
    - knowledge-ecosystem.qmd
    - part: "END"
    - summary.qmd
    - references.qmd

licence: GNU General Public License v3.0
      
bibliography: references.bib
csl: psychological-bulletin.csl

format:
  html:
    theme: cosmo
    link-external-icon: true
    link-external-newwindow: true
    number-sections: true

editor: visual
