project:
  type: book
  output-dir: docs

book:
  title: "The research report: why, what and how"
  author: "Rob Davies"
  date: "2023-10-30"
  chapters:
    - index.qmd
    - part: "The research report"
    - intro.qmd
    - what.qmd
    - how.qmd
    - part: "Making the most of your skills"
    - visualization.qmd
    - ecosystem.qmd
    - part: "End"
    - summary.qmd
    - references.qmd
      
bibliography: references.bib
csl: psychological-bulletin.csl

format:
  html:
    theme: cosmo
    link-external-icon: true
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt

editor: visual
