project:
  type: book
  output-dir: docs

book:
  title: "Psychological data analysis for graduate students: *PSYC401*"
  number-sections: true
  author: 
    name: "Rob Davies"
    affiliation: "Department of Psychology, Lancaster University"
    email: r.davies1@lancaster.ac.uk
  date: "2023-10-01"
  chapters:
    - index.qmd
    - part: "DATA ANALYSIS"
    - visualization.qmd
    - part: "THE RESEARCH REPORT ASSIGNMENT"
    - intro.qmd
    - what.qmd
    - how.qmd
    - part: "MAKING THE MOST OF R"
    - knowledge-ecosystem.qmd
    - part: "END"
    - summary.qmd
    - references.qmd

licence: GNU General Public License v3.0
      
bibliography: references.bib
csl: psychological-bulletin.csl

format:
  html:
    theme: cosmo
    link-external-icon: true
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt

editor: visual
