<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Psychological data analysis for graduate students: PSYC401 - 5&nbsp; Introduction to the linear model</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./lm-dev.html" rel="next">
<link href="./visualization.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./lm-intro.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Introduction to the linear model</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Psychological data analysis for graduate students: <em>PSYC401</em></a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Preface: Our approach</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">DATA ANALYSIS</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hypotheses-associations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Hypotheses and associations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./visualization-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Introduction to visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lm-intro.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Introduction to the linear model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lm-dev.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Developing the linear model</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">THE RESEARCH REPORT ASSIGNMENT</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./report-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">The research report assignment: Outline introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Reasons why we do the research report assignment: What you will learn</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./what.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">What you have to do</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./how.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">How you can do it</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">MAKING THE MOST OF R</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./knowledge-ecosystem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">The R knowledge ecosystem and how to help yourself</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">END</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-lm-intro-overview" id="toc-sec-lm-intro-overview" class="nav-link active" data-scroll-target="#sec-lm-intro-overview"><span class="header-section-number">5.1</span> Overview</a></li>
  <li><a href="#sec-lm-intro-goals" id="toc-sec-lm-intro-goals" class="nav-link" data-scroll-target="#sec-lm-intro-goals"><span class="header-section-number">5.2</span> Our learning goals</a>
  <ul class="collapse">
  <li><a href="#using-the-linear-model-to-answer-research-questions" id="toc-using-the-linear-model-to-answer-research-questions" class="nav-link" data-scroll-target="#using-the-linear-model-to-answer-research-questions"><span class="header-section-number">5.2.1</span> Using the linear model to answer research questions</a></li>
  </ul></li>
  <li><a href="#sec-lm-intro-resources" id="toc-sec-lm-intro-resources" class="nav-link" data-scroll-target="#sec-lm-intro-resources"><span class="header-section-number">5.3</span> Learning resources</a>
  <ul class="collapse">
  <li><a href="#sec-lm-intro-lectures" id="toc-sec-lm-intro-lectures" class="nav-link" data-scroll-target="#sec-lm-intro-lectures"><span class="header-section-number">5.3.1</span> Lectures</a></li>
  <li><a href="#sec-lm-intro-practical" id="toc-sec-lm-intro-practical" class="nav-link" data-scroll-target="#sec-lm-intro-practical"><span class="header-section-number">5.3.2</span> Practical materials</a></li>
  <li><a href="#sec-lm-intro-practical-workbook" id="toc-sec-lm-intro-practical-workbook" class="nav-link" data-scroll-target="#sec-lm-intro-practical-workbook"><span class="header-section-number">5.3.3</span> The workbook</a></li>
  <li><a href="#the-data-files" id="toc-the-data-files" class="nav-link" data-scroll-target="#the-data-files"><span class="header-section-number">5.3.4</span> The data files</a></li>
  <li><a href="#the-answers" id="toc-the-answers" class="nav-link" data-scroll-target="#the-answers"><span class="header-section-number">5.3.5</span> The answers</a></li>
  </ul></li>
  <li><a href="#sec-lm-intro-notes" id="toc-sec-lm-intro-notes" class="nav-link" data-scroll-target="#sec-lm-intro-notes"><span class="header-section-number">5.4</span> Lecture notes</a>
  <ul class="collapse">
  <li><a href="#week-9-focus-on-the-linear-model" id="toc-week-9-focus-on-the-linear-model" class="nav-link" data-scroll-target="#week-9-focus-on-the-linear-model"><span class="header-section-number">5.4.1</span> Week 9: Focus on the linear model</a></li>
  <li><a href="#analyze-visualize-present" id="toc-analyze-visualize-present" class="nav-link" data-scroll-target="#analyze-visualize-present"><span class="header-section-number">5.4.2</span> Analyze + visualize + present</a></li>
  <li><a href="#the-linear-model-our-aims" id="toc-the-linear-model-our-aims" class="nav-link" data-scroll-target="#the-linear-model-our-aims"><span class="header-section-number">5.4.3</span> The linear model: our aims</a></li>
  <li><a href="#using-the-linear-model-to-answer-research-questions-1" id="toc-using-the-linear-model-to-answer-research-questions-1" class="nav-link" data-scroll-target="#using-the-linear-model-to-answer-research-questions-1"><span class="header-section-number">5.4.4</span> Using the linear model to answer research questions</a></li>
  <li><a href="#thinking-about-relationships-in-psychologial-science" id="toc-thinking-about-relationships-in-psychologial-science" class="nav-link" data-scroll-target="#thinking-about-relationships-in-psychologial-science"><span class="header-section-number">5.4.5</span> Thinking about relationships in psychologial science</a></li>
  <li><a href="#now-consider-our-research-aims-in-the-context-of-the-health-comprehension-project" id="toc-now-consider-our-research-aims-in-the-context-of-the-health-comprehension-project" class="nav-link" data-scroll-target="#now-consider-our-research-aims-in-the-context-of-the-health-comprehension-project"><span class="header-section-number">5.4.6</span> Now consider our research aims in the <em>context</em> of the health comprehension project</a></li>
  <li><a href="#health-comprehension-project-questions-and-analyses" id="toc-health-comprehension-project-questions-and-analyses" class="nav-link" data-scroll-target="#health-comprehension-project-questions-and-analyses"><span class="header-section-number">5.4.7</span> Health comprehension project: questions and analyses</a></li>
  <li><a href="#context-individual-differences-theory-of-comprehension-success" id="toc-context-individual-differences-theory-of-comprehension-success" class="nav-link" data-scroll-target="#context-individual-differences-theory-of-comprehension-success"><span class="header-section-number">5.4.8</span> Context: Individual differences theory of comprehension success</a></li>
  <li><a href="#the-measurement-context-where-the-data-come-from" id="toc-the-measurement-context-where-the-data-come-from" class="nav-link" data-scroll-target="#the-measurement-context-where-the-data-come-from"><span class="header-section-number">5.4.9</span> The measurement context: Where the data come from</a></li>
  <li><a href="#reflect-the-kinds-of-critical-evaluation-questions-you-can-ask-yourself" id="toc-reflect-the-kinds-of-critical-evaluation-questions-you-can-ask-yourself" class="nav-link" data-scroll-target="#reflect-the-kinds-of-critical-evaluation-questions-you-can-ask-yourself"><span class="header-section-number">5.4.10</span> Reflect: The kinds of critical evaluation questions you can ask yourself</a></li>
  <li><a href="#reflect-as-we-move-into-thinking-about-the-data-analysis-we-need-to-identify-our-assumptions" id="toc-reflect-as-we-move-into-thinking-about-the-data-analysis-we-need-to-identify-our-assumptions" class="nav-link" data-scroll-target="#reflect-as-we-move-into-thinking-about-the-data-analysis-we-need-to-identify-our-assumptions"><span class="header-section-number">5.4.11</span> Reflect: As we move into thinking about the data analysis, we need to identify our assumptions</a></li>
  <li><a href="#we-need-to-think-about-the-derivation-chain" id="toc-we-need-to-think-about-the-derivation-chain" class="nav-link" data-scroll-target="#we-need-to-think-about-the-derivation-chain"><span class="header-section-number">5.4.12</span> We need to think about the derivation chain</a></li>
  <li><a href="#questions-assumptions-predictions" id="toc-questions-assumptions-predictions" class="nav-link" data-scroll-target="#questions-assumptions-predictions"><span class="header-section-number">5.4.13</span> Questions, assumptions, predictions</a></li>
  <li><a href="#one-way-of-thinking-about-the-association-is-to-visualize-it" id="toc-one-way-of-thinking-about-the-association-is-to-visualize-it" class="nav-link" data-scroll-target="#one-way-of-thinking-about-the-association-is-to-visualize-it"><span class="header-section-number">5.4.14</span> One way of thinking about the association is to visualize it</a></li>
  <li><a href="#predicted-association-as-expected-change-in-average-outcome" id="toc-predicted-association-as-expected-change-in-average-outcome" class="nav-link" data-scroll-target="#predicted-association-as-expected-change-in-average-outcome"><span class="header-section-number">5.4.15</span> Predicted association as <em>expected</em> change in average outcome</a></li>
  <li><a href="#how-do-we-estimate-the-association-between-two-variables" id="toc-how-do-we-estimate-the-association-between-two-variables" class="nav-link" data-scroll-target="#how-do-we-estimate-the-association-between-two-variables"><span class="header-section-number">5.4.16</span> How do we <em>estimate</em> the association between two variables?</a></li>
  <li><a href="#the-sentence-structure-of-models-in-r" id="toc-the-sentence-structure-of-models-in-r" class="nav-link" data-scroll-target="#the-sentence-structure-of-models-in-r"><span class="header-section-number">5.4.17</span> The sentence structure of models in R</a></li>
  <li><a href="#results-how-does-the-outcome-vary-in-relation-to-the-predictor" id="toc-results-how-does-the-outcome-vary-in-relation-to-the-predictor" class="nav-link" data-scroll-target="#results-how-does-the-outcome-vary-in-relation-to-the-predictor"><span class="header-section-number">5.4.18</span> Results: How does the outcome vary in relation to the predictor?</a></li>
  <li><a href="#these-coefficients-build-a-line" id="toc-these-coefficients-build-a-line" class="nav-link" data-scroll-target="#these-coefficients-build-a-line"><span class="header-section-number">5.4.19</span> These <em>coefficients</em> build a line</a></li>
  <li><a href="#so-now-we-need-to-think-about-straight-lines" id="toc-so-now-we-need-to-think-about-straight-lines" class="nav-link" data-scroll-target="#so-now-we-need-to-think-about-straight-lines"><span class="header-section-number">5.4.20</span> So now we need to think about straight lines</a></li>
  <li><a href="#lets-draw-it" id="toc-lets-draw-it" class="nav-link" data-scroll-target="#lets-draw-it"><span class="header-section-number">5.4.21</span> Let’s draw it</a></li>
  <li><a href="#we-can-understand-the-line-as-representing-a-set-of-predictions" id="toc-we-can-understand-the-line-as-representing-a-set-of-predictions" class="nav-link" data-scroll-target="#we-can-understand-the-line-as-representing-a-set-of-predictions"><span class="header-section-number">5.4.22</span> We can understand the line as representing a set of predictions</a></li>
  </ul></li>
  <li><a href="#we-can-understand-the-line-as-representing-a-set-of-predictions-1" id="toc-we-can-understand-the-line-as-representing-a-set-of-predictions-1" class="nav-link" data-scroll-target="#we-can-understand-the-line-as-representing-a-set-of-predictions-1"><span class="header-section-number">5.5</span> We can understand the line as representing a set of predictions</a>
  <ul class="collapse">
  <li><a href="#the-linear-model-allows-us-to-predict-the-average-outcome-we-can-expect-given-any-value-of-the-predictor" id="toc-the-linear-model-allows-us-to-predict-the-average-outcome-we-can-expect-given-any-value-of-the-predictor" class="nav-link" data-scroll-target="#the-linear-model-allows-us-to-predict-the-average-outcome-we-can-expect-given-any-value-of-the-predictor"><span class="header-section-number">5.5.1</span> The linear model allows us to predict the average outcome we can expect given <em>any</em> value of the predictor</a></li>
  <li><a href="#we-could-draw-a-variety-of-different-model-prediction-lines-how-do-we-pick-the-right-one" id="toc-we-could-draw-a-variety-of-different-model-prediction-lines-how-do-we-pick-the-right-one" class="nav-link" data-scroll-target="#we-could-draw-a-variety-of-different-model-prediction-lines-how-do-we-pick-the-right-one"><span class="header-section-number">5.5.2</span> We could draw a variety of different model prediction lines: how do we pick the <em>right</em> one?</a></li>
  <li><a href="#we-could-draw-a-variety-of-different-model-prediction-lines-how-do-we-pick-the-right-one-1" id="toc-we-could-draw-a-variety-of-different-model-prediction-lines-how-do-we-pick-the-right-one-1" class="nav-link" data-scroll-target="#we-could-draw-a-variety-of-different-model-prediction-lines-how-do-we-pick-the-right-one-1"><span class="header-section-number">5.5.3</span> We could draw a variety of different model prediction lines: how do we pick the <em>right</em> one?</a></li>
  <li><a href="#linear-models-are-typically-estimated-given-sample-data" id="toc-linear-models-are-typically-estimated-given-sample-data" class="nav-link" data-scroll-target="#linear-models-are-typically-estimated-given-sample-data"><span class="header-section-number">5.5.4</span> Linear models are typically estimated given sample data</a></li>
  <li><a href="#linear-models-are-typically-estimated-given-sample-data-1" id="toc-linear-models-are-typically-estimated-given-sample-data-1" class="nav-link" data-scroll-target="#linear-models-are-typically-estimated-given-sample-data-1"><span class="header-section-number">5.5.5</span> Linear models are typically estimated given sample data</a></li>
  <li><a href="#we-can-derive-the-formulas-used-to-calculate-the-estimates-using-calculus" id="toc-we-can-derive-the-formulas-used-to-calculate-the-estimates-using-calculus" class="nav-link" data-scroll-target="#we-can-derive-the-formulas-used-to-calculate-the-estimates-using-calculus"><span class="header-section-number">5.5.6</span> We can derive the formulas used to calculate the estimates using calculus</a></li>
  <li><a href="#what-do-the-prediction-errors-the-residuals-look-like" id="toc-what-do-the-prediction-errors-the-residuals-look-like" class="nav-link" data-scroll-target="#what-do-the-prediction-errors-the-residuals-look-like"><span class="header-section-number">5.5.7</span> What do the prediction errors – the residuals – look like?</a></li>
  <li><a href="#what-the-prediction-errors-look-like" id="toc-what-the-prediction-errors-look-like" class="nav-link" data-scroll-target="#what-the-prediction-errors-look-like"><span class="header-section-number">5.5.8</span> What the prediction errors look like</a></li>
  </ul></li>
  <li><a href="#what-the-prediction-errors-look-like-1" id="toc-what-the-prediction-errors-look-like-1" class="nav-link" data-scroll-target="#what-the-prediction-errors-look-like-1"><span class="header-section-number">5.6</span> What the prediction errors look like</a>
  <ul class="collapse">
  <li><a href="#what-the-prediction-errors-look-like-2" id="toc-what-the-prediction-errors-look-like-2" class="nav-link" data-scroll-target="#what-the-prediction-errors-look-like-2"><span class="header-section-number">5.6.1</span> What the prediction errors look like</a></li>
  <li><a href="#we-typically-assume-that-the-residuals-are-normally-distributed" id="toc-we-typically-assume-that-the-residuals-are-normally-distributed" class="nav-link" data-scroll-target="#we-typically-assume-that-the-residuals-are-normally-distributed"><span class="header-section-number">5.6.2</span> We typically assume that the residuals are normally distributed</a></li>
  <li><a href="#so-we-pick-the-line-that-minimizes-the-residuals-the-mismatch-between-predicted-and-observed-outcomes" id="toc-so-we-pick-the-line-that-minimizes-the-residuals-the-mismatch-between-predicted-and-observed-outcomes" class="nav-link" data-scroll-target="#so-we-pick-the-line-that-minimizes-the-residuals-the-mismatch-between-predicted-and-observed-outcomes"><span class="header-section-number">5.6.3</span> So: We pick the line that minimizes the residuals – the mismatch between predicted and observed outcomes</a></li>
  <li><a href="#identifying-the-key-information-in-the-linear-model-results" id="toc-identifying-the-key-information-in-the-linear-model-results" class="nav-link" data-scroll-target="#identifying-the-key-information-in-the-linear-model-results"><span class="header-section-number">5.6.4</span> Identifying the key information in the linear model results</a></li>
  <li><a href="#for-the-effect-of-vocabulary-shipley-we-have" id="toc-for-the-effect-of-vocabulary-shipley-we-have" class="nav-link" data-scroll-target="#for-the-effect-of-vocabulary-shipley-we-have"><span class="header-section-number">5.6.5</span> For the effect of vocabulary (SHIPLEY), we have:</a></li>
  <li><a href="#identifying-the-key-information-in-the-results" id="toc-identifying-the-key-information-in-the-results" class="nav-link" data-scroll-target="#identifying-the-key-information-in-the-results"><span class="header-section-number">5.6.6</span> Identifying the key information in the results</a></li>
  <li><a href="#the-t-tests-in-the-linear-model" id="toc-the-t-tests-in-the-linear-model" class="nav-link" data-scroll-target="#the-t-tests-in-the-linear-model"><span class="header-section-number">5.6.7</span> The t-tests in the linear model</a></li>
  <li><a href="#the-t-tests-in-the-linear-model-1" id="toc-the-t-tests-in-the-linear-model-1" class="nav-link" data-scroll-target="#the-t-tests-in-the-linear-model-1"><span class="header-section-number">5.6.8</span> The t-tests in the linear model</a></li>
  <li><a href="#the-t-tests-in-the-linear-model-2" id="toc-the-t-tests-in-the-linear-model-2" class="nav-link" data-scroll-target="#the-t-tests-in-the-linear-model-2"><span class="header-section-number">5.6.9</span> The t-tests in the linear model</a></li>
  <li><a href="#identifying-the-key-information-in-the-results-1" id="toc-identifying-the-key-information-in-the-results-1" class="nav-link" data-scroll-target="#identifying-the-key-information-in-the-results-1"><span class="header-section-number">5.6.10</span> Identifying the key information in the results</a></li>
  <li><a href="#r-squared-what-is-it-an-indicator-of-the-proportion-of-outcome-variation-we-can-predict" id="toc-r-squared-what-is-it-an-indicator-of-the-proportion-of-outcome-variation-we-can-predict" class="nav-link" data-scroll-target="#r-squared-what-is-it-an-indicator-of-the-proportion-of-outcome-variation-we-can-predict"><span class="header-section-number">5.6.11</span> R-squared – what is it? – an indicator of the proportion of outcome variation we can predict</a></li>
  <li><a href="#r-squared-as-an-indicator-of-the-proportion-of-the-outcome-variation-we-can-predict" id="toc-r-squared-as-an-indicator-of-the-proportion-of-the-outcome-variation-we-can-predict" class="nav-link" data-scroll-target="#r-squared-as-an-indicator-of-the-proportion-of-the-outcome-variation-we-can-predict"><span class="header-section-number">5.6.12</span> R-squared as an indicator of the proportion of the outcome variation we can predict</a></li>
  <li><a href="#r-squared-as-an-indicator-of-the-proportion-of-the-outcome-variation-we-can-predict-1" id="toc-r-squared-as-an-indicator-of-the-proportion-of-the-outcome-variation-we-can-predict-1" class="nav-link" data-scroll-target="#r-squared-as-an-indicator-of-the-proportion-of-the-outcome-variation-we-can-predict-1"><span class="header-section-number">5.6.13</span> R-squared as an indicator of the proportion of the outcome variation we can predict</a></li>
  <li><a href="#identifying-the-key-information-in-the-results-2" id="toc-identifying-the-key-information-in-the-results-2" class="nav-link" data-scroll-target="#identifying-the-key-information-in-the-results-2"><span class="header-section-number">5.6.14</span> Identifying the key information in the results</a></li>
  <li><a href="#reporting-the-results-of-a-linear-model" id="toc-reporting-the-results-of-a-linear-model" class="nav-link" data-scroll-target="#reporting-the-results-of-a-linear-model"><span class="header-section-number">5.6.15</span> Reporting the results of a linear model</a></li>
  <li><a href="#the-language-and-style-of-reporting-linear-model-results" id="toc-the-language-and-style-of-reporting-linear-model-results" class="nav-link" data-scroll-target="#the-language-and-style-of-reporting-linear-model-results"><span class="header-section-number">5.6.16</span> The language and style of reporting linear model results</a></li>
  <li><a href="#look-at-what-we-do-with-the-text" id="toc-look-at-what-we-do-with-the-text" class="nav-link" data-scroll-target="#look-at-what-we-do-with-the-text"><span class="header-section-number">5.6.17</span> Look at what we do with the text</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">5.7</span> Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-lm-intro-intro" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Introduction to the linear model</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="sec-lm-intro-overview" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="sec-lm-intro-overview"><span class="header-section-number">5.1</span> Overview</h2>
<p>Welcome to our overview of the materials you will work with in our class introducing you to the <strong>linear model</strong> in <em>PSYC401</em> Week 9.</p>
<p>We will return to locate our learning in the context of the <em>Clearly understood</em> project. We will present our PSYC401 lessons in the context of this research project because we think that this context will help you to make sense of the data (as we explain in <a href="index.html"><span>Chapter&nbsp;1</span></a>).</p>
<p>Remember: it is unclear how to make health communication more effective. The problem is that we are not sure how health information should be communicated so that everyone can understand it. This is why we ask the research questions:</p>
<ol type="1">
<li>What person attributes predict success in understanding?</li>
<li>Can people accurately evaluate whether they correctly understand written health information?</li>
</ol>
<p>As we work together, we will be revisiting some of the ideas and techniques you have seen in previous classes. This is to give you the opportunity to consolidate your learning. We will be extending your development with some new ideas to strengthen your skills.</p>
<p>You can read a bit more about the project and the project data in <a href="hypotheses-associations.html"><span>Chapter&nbsp;1</span></a>.</p>
</section>
<section id="sec-lm-intro-goals" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="sec-lm-intro-goals"><span class="header-section-number">5.2</span> Our learning goals</h2>
<p>This week, we focus on learning how to predict people: predicting observations about us (e.g., our attributes) or about the things we make or do. To do this, we will learn to think about and work with <em>linear models</em>.</p>
<p><strong>Our learning objectives: — what are we learning about?</strong></p>
<section id="using-the-linear-model-to-answer-research-questions" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="using-the-linear-model-to-answer-research-questions"><span class="header-section-number">5.2.1</span> Using the linear model to answer research questions</h3>
<ul>
<li>We will learn how to:</li>
</ul>
<ol type="1">
<li>code linear models</li>
<li>identify and interpret model statistics</li>
<li>critically evaluate the results</li>
<li>communicate the results</li>
</ol>
<ul>
<li>Because we often want to know about relationships, asking questions like:</li>
</ul>
<ol type="1">
<li>Does variation in X predict variation in Y?</li>
<li>What are the factors that influence outcome Y?</li>
<li>Is a theoretical model consistent with observed behaviour?</li>
</ol>
</section>
</section>
<section id="sec-lm-intro-resources" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="sec-lm-intro-resources"><span class="header-section-number">5.3</span> Learning resources</h2>
<p>You will see in the <em>next section</em> links to the lectures we created both to explain the concepts we want to help you to learn about, and to explain the practical data analysis skills we want to help you to develop (<a href="#sec-lm-intro-lectures"><span>Section&nbsp;5.3.1</span></a>). We <em>then</em> share links to information about the practical materials we have provided to help you to practise those skills (<a href="#sec-lm-intro-practical"><span>Section&nbsp;5.3.2</span></a>).</p>
<p>All the links to the lecture videos, the lecture slides, and everything you need for your practical work can <em>also</em> be found in the Week 9 files folder on Moodle <a href="https://modules.lancaster.ac.uk/course/view.php?id=40622#coursecontentcollapse10" target="_blank">here</a></p>
<p>In <a href="#sec-lm-intro-notes"><span>Section&nbsp;5.4</span></a>, we present the lecture slide points.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Linked resources</strong> include:</p>
<ul>
<li>In <a href="hypotheses-associations.html"><span>Chapter&nbsp;1</span></a>, we present an overview of the materials we have shared to support your development of critical thinking in relation to associations, and to support your learning about conducting correlation-based analyses of associations.</li>
<li>It may help you to revise these materials.</li>
</ul>
</div>
</div>
<section id="sec-lm-intro-lectures" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="sec-lm-intro-lectures"><span class="header-section-number">5.3.1</span> Lectures</h3>
<p>The lecture material for this week is presented in four short parts. Click on a link and your browser should open a tab showing the <em>Panopto</em> video for the lecture part.</p>
<p><a href="https://lancaster.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=9d4653c0-9ea2-4437-a74f-af5f00b2fd2e" target="_blank">Part 1 of 4</a></p>
<p><a href="https://lancaster.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=71eaffe1-5066-425c-9ce2-af5f00b79730" target="_blank">Part 2 of 4</a></p>
<p><a href="https://lancaster.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=a08f12af-606a-4be0-90ae-af5f00bc1491" target="_blank">Part 3 of 4</a></p>
<p><a href="https://lancaster.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=a16c627e-609b-49db-b683-af5f00bfb15f" target="_blank">Part 4 of 4</a></p>
<p>You can download the slides we presented in the lecture in two different formats, depending on what you think will be most useful to you:</p>
<ul>
<li>Download the slides exactly as they appear in the lecture from <a href="files/401-linear-model-intro.html">this link</a>. The .html file can be opened and viewed in any web browser (e.g., Chrome, Firefox, Safari).</li>
<li>Or you can download a printable Word .docx presentation of the slides from <a href="files/401-linear-model-intro-printable-edit.docx">this link</a>. The .docx can be opened in Microsoft Word. The figures will not appear exactly as they do in the lecture recording because Word cannot cope with images so well but the trade-off is that you get a document you can print and edit to add notes.</li>
</ul>
</section>
<section id="sec-lm-intro-practical" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="sec-lm-intro-practical"><span class="header-section-number">5.3.2</span> Practical materials</h3>
<p>We have collected the practical materials together into a folder.</p>
<p>The folder includes the data files:</p>
<ul>
<li><code>study-one-general-participants.csv</code></li>
<li><code>study-two-general-participants.csv</code></li>
</ul>
<p>and .R code files:</p>
<ul>
<li><code>401-lm-intro-how-to.R</code></li>
<li><code>401-lm-intro-workbook.R</code></li>
</ul>
<p>You will use these files for your practical learning.</p>
<p>You can download the .R files and the data .csv files in a single folder, using the link <a href="files/PSYC401_lm-intro_materials.zip">here</a>.</p>
<p>Or you can download the files as individual files from the module <a href="https://modules.lancaster.ac.uk/course/view.php?id=40622#coursecontentcollapse10" target="_blank">Moodle page for PSYC401</a>.</p>
<p>Once you have downloaded the file folder, you will need to upload it to the R-Studio server to access and use the R files.</p>
<section id="sec-lm-intro-practical-how-to" class="level4" data-number="5.3.2.1">
<h4 data-number="5.3.2.1" class="anchored" data-anchor-id="sec-lm-intro-practical-how-to"><span class="header-section-number">5.3.2.1</span> The how-to guide</h4>
<p>In the <code>how-to</code> guide:</p>
<ul>
<li><code>401-lm-intro-how-to.R</code></li>
</ul>
<p>we show you how to do everything you need to do in the practical workbook (see <a href="#sec-lm-intro-practical-workbook"><span>Section&nbsp;5.3.3</span></a>). The guide comprises an .R file <code>401-lm-intro-how-to.R</code> with code and advice.</p>
<p>The code in the .R file was written to work with the data file</p>
<ul>
<li><code>study-one-general-participants.csv</code>.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>Work through the steps in the <code>how-to</code> guide first, this practice will help you to understand what you need to do for the <code>workbook</code> tasks.</p></li>
<li><p>The <code>how-to</code> guide and the <code>workbook</code> have similar structures. This is intentional: so that you can copy and <em>adapt</em> code from the <code>how-to</code> guide to do the practical tasks in the <code>workbook</code>.</p></li>
</ul>
</div>
</div>
</section>
</section>
<section id="sec-lm-intro-practical-workbook" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="sec-lm-intro-practical-workbook"><span class="header-section-number">5.3.3</span> The workbook</h3>
<p>In the <code>workbook</code>:</p>
<ul>
<li><code>401-lm-intro-workbook.R</code></li>
</ul>
<p>you will work with the data file</p>
<ul>
<li><code>study-two-general-participants.csv</code></li>
</ul>
<p>We split .R scripts into parts, tasks and questions.</p>
<p>For this class on linear models, our practical materials have two aims:</p>
<ol type="1">
<li>Helping you to learn how to use linear models to address questions about associations, questions like “What person attributes predict success in understanding?”;</li>
<li>Helping you to learn how to interpret linear model results, including how to work with data visualizations displaying distributions or associations.</li>
</ol>
<p>We progress a series of parts, each designed to enable learning or developing concepts or skills:</p>
<ul>
<li><strong>Part 3</strong> refreshes your development of skills for working with histogram-based visualizations of data distributions. Here, we are aiming to advance your skills so that you can develop nicer looking histograms that present more accurate accounts of distributions (by showing the full range of potential values), and so that you can annotate histograms to direct the attention of your audience <a href="visualization-intro.html">as we discuss in&nbsp;<span>3</span></a>.</li>
<li><strong>Part 4</strong> helps you to learn how you can present grids of histograms for easy comparison of variable distributions.</li>
<li><strong>Part 5</strong> refreshes your development of skills for working with scatterplot-based visualizations of associations or of the relationships between two or more numeric variables. We look at how you can edit the appearance of the plots, element by element. And we look at how you can produce grids of scatterplots, again, to enable comparisons — here, of the potential relationships between one outcome and multiple other variables.</li>
<li><strong>Part 6</strong> offers the opportunity to revise the calculation and interpretation of correlation analyses.</li>
<li><strong>Part 7</strong> provides exercises designed to help you to learn how to conduct linear model analyses.</li>
<li><strong>Part 8</strong> helps you to develop skills in calculating and presenting model predictions.</li>
<li><strong>Part 9</strong> is optional and focuses on working with R-community information to find out how to annotate plots using <code>geom_vline()</code> or <code>geom_hline()</code>.</li>
</ul>
<p>The activity <code>401-lm-intro-workbook.R</code> file takes you through the tasks, one by one.</p>
<p>If you are unsure about what you need to do, check the advice in <code>401-lm-intro-how-to.R</code>.</p>
<p>You will see that you can match a task in the <code>activity</code> to the same task in the <code>how-to</code>. The <code>how-to</code> shows you what function you need and how you should write the function code. You will need to change the names of the data-set or the variables to complete the tasks in the activity.</p>
</section>
<section id="the-data-files" class="level3" data-number="5.3.4">
<h3 data-number="5.3.4" class="anchored" data-anchor-id="the-data-files"><span class="header-section-number">5.3.4</span> The data files</h3>
<p>Each of the data files we will work with has a similar structure.</p>
<p>Here are what the first few rows in the data file <code>study-two-general-participants.csv</code> looks like:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">participant_ID</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean.acc</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean.self</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">study</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AGE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SHIPLEY</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">HLVA</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">FACTOR3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">QRITOTAL</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">GENDER</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">EDUCATION</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">ETHNICITY</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">studytwo.1</td>
<td style="text-align: right;">0.4107143</td>
<td style="text-align: right;">6.071429</td>
<td style="text-align: left;">studytwo</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">Higher</td>
<td style="text-align: left;">Asian</td>
</tr>
<tr class="even">
<td style="text-align: left;">studytwo.10</td>
<td style="text-align: right;">0.6071429</td>
<td style="text-align: right;">8.500000</td>
<td style="text-align: left;">studytwo</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">58</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">Secondary</td>
<td style="text-align: left;">White</td>
</tr>
<tr class="odd">
<td style="text-align: left;">studytwo.100</td>
<td style="text-align: right;">0.8750000</td>
<td style="text-align: right;">8.928571</td>
<td style="text-align: left;">studytwo</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">20</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">Higher</td>
<td style="text-align: left;">White</td>
</tr>
<tr class="even">
<td style="text-align: left;">studytwo.101</td>
<td style="text-align: right;">0.9642857</td>
<td style="text-align: right;">8.500000</td>
<td style="text-align: left;">studytwo</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">14</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">Higher</td>
<td style="text-align: left;">White</td>
</tr>
<tr class="odd">
<td style="text-align: left;">studytwo.102</td>
<td style="text-align: right;">0.7142857</td>
<td style="text-align: right;">7.071429</td>
<td style="text-align: left;">studytwo</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">52</td>
<td style="text-align: right;">18</td>
<td style="text-align: left;">Male</td>
<td style="text-align: left;">Higher</td>
<td style="text-align: left;">White</td>
</tr>
<tr class="even">
<td style="text-align: left;">studytwo.103</td>
<td style="text-align: right;">0.7678571</td>
<td style="text-align: right;">5.071429</td>
<td style="text-align: left;">studytwo</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">54</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">Further</td>
<td style="text-align: left;">White</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>You can see the columns:</p>
<ul>
<li><code>participant_ID</code> participant code</li>
<li><code>mean.acc</code> average accuracy of response to questions testing understanding of health guidance</li>
<li><code>mean.self</code> average self-rated accuracy of understanding of health guidance</li>
<li><code>study</code> variable coding for what study the data were collected in</li>
<li><code>AGE</code> age in years</li>
<li><code>HLVA</code> health literacy test score</li>
<li><code>SHIPLEY</code> vocabulary knowledge test score</li>
<li><code>FACTOR3</code> reading strategy survey score</li>
<li><code>GENDER</code> gender code</li>
<li><code>EDUCATION</code> education level code</li>
<li><code>ETHNICITY</code> ethnicity (Office National Statistics categories) code</li>
</ul>
</section>
<section id="the-answers" class="level3" data-number="5.3.5">
<h3 data-number="5.3.5" class="anchored" data-anchor-id="the-answers"><span class="header-section-number">5.3.5</span> The answers</h3>
<p>After the practical class, you will be able to download the answers version of the <code>workbook</code> here.</p>
<!-- [401-visualization-workbook-answers.R](files/401-visualization-workbook-answers.R) -->
<p>The answers version will present my answers for questions, and some extra information where that is helpful.</p>
</section>
</section>
<section id="sec-lm-intro-notes" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="sec-lm-intro-notes"><span class="header-section-number">5.4</span> Lecture notes</h2>
<p>Some people find it easier to read notes than to watch video recordings. This is why we also include the lecture notes here.</p>
<!-- ::: callout-tip -->
<!-- In these notes, I provide notes on the code steps that result in plots. -->
<!-- -   Click on the `Notes` tab to see them. -->
<!-- ::: -->
<section id="week-9-focus-on-the-linear-model" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="week-9-focus-on-the-linear-model"><span class="header-section-number">5.4.1</span> Week 9: Focus on the linear model</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="lm-intro_files/figure-html/abline-predict-random-1-1.png" class="img-fluid" alt="The figure presents a scatterplot indicating the association between variables mean accuracy (on y-axis) and vocabulary (x-axis) scores. The points are shown in grey, and clustered such that higher vocabulary scores tend to be associated with higher accuracy scores. The trend is indicated by a thick red line. In the background, a fan of light pink lines indicate possible ways to capture the trend of the association." width="480"></p>
</div>
</div>
</section>
<section id="analyze-visualize-present" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="analyze-visualize-present"><span class="header-section-number">5.4.2</span> Analyze + visualize + present</h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-pipeline" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<div>
<svg width="672" height="480" viewbox="0.00 0.00 267.00 264.00" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" style="; max-width: none; max-height: none">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 260)">
<title>
Q
</title>
<polygon fill="white" stroke="transparent" points="-4,4 -4,-260 263,-260 263,4 -4,4"></polygon> <g id="clust1" class="cluster">
<title>
cluster_R
</title>
<polygon fill="none" stroke="black" points="8,-65 8,-118 251,-118 251,-65 8,-65"></polygon> </g> <!-- nd_1 --> <g id="node1" class="node">
<title>
nd_1
</title>
<polygon fill="none" stroke="black" points="35.24,-219.5 35.24,-255.5 122.76,-255.5 122.76,-219.5 35.24,-219.5"></polygon> <text text-anchor="middle" x="79" y="-233.3" font-family="Times,serif" font-size="14.00">Get raw data</text> </g> <!-- nd_2 --> <g id="node2" class="node">
<title>
nd_2
</title>
<polygon fill="none" stroke="black" points="44.37,-146.5 44.37,-182.5 113.63,-182.5 113.63,-146.5 44.37,-146.5"></polygon> <text text-anchor="middle" x="79" y="-160.3" font-family="Times,serif" font-size="14.00">Tidy data</text> </g> <!-- nd_1&#45;&gt;nd_2 --> <g id="edge6" class="edge">
<title>
nd_1-&gt;nd_2
</title>
<path fill="none" stroke="grey" d="M79,-219.31C79,-211.29 79,-201.55 79,-192.57"></path> <polygon fill="grey" stroke="grey" points="82.5,-192.53 79,-182.53 75.5,-192.53 82.5,-192.53"></polygon> </g> <!-- nd_3_l --> <g id="node4" class="node">
<title>
nd_3_l
</title>
<polygon fill="none" stroke="red" points="174.57,-73.5 174.57,-109.5 243.43,-109.5 243.43,-73.5 174.57,-73.5"></polygon> <text text-anchor="middle" x="209" y="-87.3" font-family="Times,serif" font-size="14.00">Visualize</text> </g> <!-- nd_2&#45;&gt;nd_3_l --> <g id="edge5" class="edge">
<title>
nd_2-&gt;nd_3_l
</title>
<path fill="none" stroke="grey" d="M112.24,-146.3C128.26,-137.9 147.71,-127.58 165,-118 166.95,-116.92 168.93,-115.81 170.94,-114.68"></path> <polygon fill="grey" stroke="grey" points="172.78,-117.66 179.74,-109.67 169.32,-111.57 172.78,-117.66"></polygon> </g> <!-- nd_3 --> <g id="node5" class="node">
<title>
nd_3
</title>
<polygon fill="none" stroke="red" points="15.68,-73.5 15.68,-109.5 78.32,-109.5 78.32,-73.5 15.68,-73.5"></polygon> <text text-anchor="middle" x="47" y="-87.3" font-family="Times,serif" font-size="14.00">Analyze</text> </g> <!-- nd_2&#45;&gt;nd_3 --> <g id="edge7" class="edge">
<title>
nd_2-&gt;nd_3
</title>
<path fill="none" stroke="grey" d="M71.25,-146.31C67.52,-138.03 62.96,-127.91 58.81,-118.69"></path> <polygon fill="grey" stroke="grey" points="61.97,-117.21 54.67,-109.53 55.59,-120.08 61.97,-117.21"></polygon> </g> <!-- nd_3_r --> <g id="node6" class="node">
<title>
nd_3_r
</title>
<polygon fill="none" stroke="black" points="95.84,-73.5 95.84,-109.5 156.16,-109.5 156.16,-73.5 95.84,-73.5"></polygon> <text text-anchor="middle" x="126" y="-87.3" font-family="Times,serif" font-size="14.00">Explore</text> </g> <!-- nd_2&#45;&gt;nd_3_r --> <g id="edge4" class="edge">
<title>
nd_2-&gt;nd_3_r
</title>
<path fill="none" stroke="grey" d="M90.38,-146.31C95.98,-137.85 102.84,-127.48 109.05,-118.11"></path> <polygon fill="grey" stroke="grey" points="112.13,-119.8 114.73,-109.53 106.29,-115.94 112.13,-119.8"></polygon> </g> <!-- nd_3_a --> <g id="node3" class="node">
<title>
nd_3_a
</title>
<polygon fill="none" stroke="black" points="131.44,-146.5 131.44,-182.5 220.56,-182.5 220.56,-146.5 131.44,-146.5"></polygon> <text text-anchor="middle" x="176" y="-160.3" font-family="Times,serif" font-size="14.00">Assumptions</text> </g> <!-- nd_3_a&#45;&gt;nd_3_l --> <g id="edge3" class="edge">
<title>
nd_3_a-&gt;nd_3_l
</title>
<path fill="none" stroke="grey" d="M183.99,-146.31C187.84,-138.03 192.54,-127.91 196.83,-118.69"></path> <polygon fill="grey" stroke="grey" points="200.04,-120.07 201.09,-109.53 193.7,-117.12 200.04,-120.07"></polygon> </g> <!-- nd_3_a&#45;&gt;nd_3 --> <g id="edge1" class="edge">
<title>
nd_3_a-&gt;nd_3
</title>
<path fill="none" stroke="grey" d="M140.5,-146.32C124.04,-138.11 104.32,-127.92 87,-118 85.28,-117.02 83.54,-116 81.79,-114.95"></path> <polygon fill="grey" stroke="grey" points="83.39,-111.83 73.03,-109.6 79.74,-117.8 83.39,-111.83"></polygon> </g> <!-- nd_3_a&#45;&gt;nd_3_r --> <g id="edge2" class="edge">
<title>
nd_3_a-&gt;nd_3_r
</title>
<path fill="none" stroke="grey" d="M163.9,-146.31C157.88,-137.77 150.49,-127.27 143.83,-117.82"></path> <polygon fill="grey" stroke="grey" points="146.61,-115.69 137.99,-109.53 140.89,-119.72 146.61,-115.69"></polygon> </g> <!-- nd_3_l&#45;&gt;nd_3 --> <g id="edge10" class="edge">
<title>
nd_3_l-&gt;nd_3
</title>
<path fill="none" stroke="transparent" d="M191.16,-109.88C181.63,-118.37 169.16,-127.55 156,-132 130.74,-140.55 121.09,-141.03 96,-132 83.54,-127.52 71.99,-118.34 63.24,-109.85"></path> </g> <!-- nd_4 --> <g id="node7" class="node">
<title>
nd_4
</title>
<polygon fill="none" stroke="red" points="99.39,-0.5 99.39,-36.5 156.61,-36.5 156.61,-0.5 99.39,-0.5"></polygon> <text text-anchor="middle" x="128" y="-14.3" font-family="Times,serif" font-size="14.00">Present</text> </g> <!-- nd_3_l&#45;&gt;nd_4 --> <g id="edge9" class="edge">
<title>
nd_3_l-&gt;nd_4
</title>
<path fill="none" stroke="grey" d="M189.39,-73.31C179.14,-64.33 166.44,-53.19 155.25,-43.39"></path> <polygon fill="grey" stroke="grey" points="157.25,-40.49 147.43,-36.53 152.64,-45.75 157.25,-40.49"></polygon> </g> <!-- nd_3&#45;&gt;nd_4 --> <g id="edge8" class="edge">
<title>
nd_3-&gt;nd_4
</title>
<path fill="none" stroke="grey" d="M66.61,-73.31C76.86,-64.33 89.56,-53.19 100.75,-43.39"></path> <polygon fill="grey" stroke="grey" points="103.36,-45.75 108.57,-36.53 98.75,-40.49 103.36,-45.75"></polygon> </g> </g>
</svg>
</div>
<figcaption class="figure-caption">Figure&nbsp;5.1: The data analysis pipeline or workflow: we focus on the linear model</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="the-linear-model-our-aims" class="level3" data-number="5.4.3">
<h3 data-number="5.4.3" class="anchored" data-anchor-id="the-linear-model-our-aims"><span class="header-section-number">5.4.3</span> The linear model: our aims</h3>
<ol type="1">
<li>Understand how to code: <code>lm(mean.acc ~ SHIPLEY)</code></li>
<li>To answer questions like: <strong>Is comprehension success influenced by vocabulary knowledge?</strong></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div id="fig-scatterplot-shipley-acc-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="lm-intro_files/figure-html/fig-scatterplot-shipley-acc-1-1.png" class="img-fluid figure-img" alt="The figure presents a scatterplot indicating the association between variables mean accuracy (on y-axis) and vocabulary (x-axis) scores. The points are shown in grey, and clustered such that higher vocabulary scores tend to be associated with higher accuracy scores. The trend is indicated by a thick red line." width="480"></p>
<figcaption class="figure-caption">Figure&nbsp;5.2: Scatterplot showing the potential association between accuracy of comprehension and vocabulary scores</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="using-the-linear-model-to-answer-research-questions-1" class="level3" data-number="5.4.4">
<h3 data-number="5.4.4" class="anchored" data-anchor-id="using-the-linear-model-to-answer-research-questions-1"><span class="header-section-number">5.4.4</span> Using the linear model to answer research questions</h3>
<ul>
<li>We will learn how to:</li>
</ul>
<ol type="1">
<li>code linear models</li>
<li>identify and interpret model statistics</li>
<li>critically evaluate the results</li>
<li>communicate the results</li>
</ol>
</section>
<section id="thinking-about-relationships-in-psychologial-science" class="level3" data-number="5.4.5">
<h3 data-number="5.4.5" class="anchored" data-anchor-id="thinking-about-relationships-in-psychologial-science"><span class="header-section-number">5.4.5</span> Thinking about relationships in psychologial science</h3>
<p>We often want to know about relationships</p>
<ul>
<li>Does variation in X predict variation in Y?</li>
<li>What are the factors that influence outcome Y?</li>
<li>Is a theoretical model consistent with observed behaviour?</li>
</ul>
</section>
<section id="now-consider-our-research-aims-in-the-context-of-the-health-comprehension-project" class="level3" data-number="5.4.6">
<h3 data-number="5.4.6" class="anchored" data-anchor-id="now-consider-our-research-aims-in-the-context-of-the-health-comprehension-project"><span class="header-section-number">5.4.6</span> Now consider our research aims in the <em>context</em> of the health comprehension project</h3>
<ol type="1">
<li>Because public health impacts depend on giving people information they can understand</li>
<li>We want to know: <strong>What makes it easy or difficult to understand written health information?</strong></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="nurse-patient-talk.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption class="figure-caption">flickr: Sasin Tipchair ‘Senior woman in wheelchair talking to a nurse in a hospital’</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="health-comprehension-project-questions-and-analyses" class="level3" data-number="5.4.7">
<h3 data-number="5.4.7" class="anchored" data-anchor-id="health-comprehension-project-questions-and-analyses"><span class="header-section-number">5.4.7</span> Health comprehension project: questions and analyses</h3>
<ol type="1">
<li>We want to know: <strong>What makes it easy or difficult to understand written health information?</strong></li>
<li>So our research questions are:</li>
</ol>
<ul>
<li>What person attributes predict success in understanding?</li>
<li>Can people accurately evaluate whether they correctly understand written health information?</li>
</ul>
<ol start="3" type="1">
<li>These kinds of research questions can be answered using methods like linear models</li>
</ol>
</section>
<section id="context-individual-differences-theory-of-comprehension-success" class="level3" data-number="5.4.8">
<h3 data-number="5.4.8" class="anchored" data-anchor-id="context-individual-differences-theory-of-comprehension-success"><span class="header-section-number">5.4.8</span> Context: Individual differences theory of comprehension success</h3>
<ul>
<li>Understanding text depends on (1.) language experience and (2.) reasoning ability <span class="citation" data-cites="freed2017">(<a href="references.html#ref-freed2017" role="doc-biblioref">Freed et al., 2017</a>)</span></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="fig-comprehension-drivers" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<div>
<svg width="672" height="480" viewbox="0.00 0.00 335.68 98.00" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" style="; max-width: none; max-height: none">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 94)">
<title>
Q
</title>
<polygon fill="white" stroke="transparent" points="-4,4 -4,-94 331.68,-94 331.68,4 -4,4"></polygon> <!-- nd_1_l --> <g id="node1" class="node">
<title>
nd_1_l
</title>
<path fill="none" stroke="black" d="M123.47,-90C123.47,-90 11.84,-90 11.84,-90 5.84,-90 -0.16,-84 -0.16,-78 -0.16,-78 -0.16,-66 -0.16,-66 -0.16,-60 5.84,-54 11.84,-54 11.84,-54 123.47,-54 123.47,-54 129.47,-54 135.47,-60 135.47,-66 135.47,-66 135.47,-78 135.47,-78 135.47,-84 129.47,-90 123.47,-90"></path> <text text-anchor="middle" x="67.66" y="-67.8" font-family="Times,serif" font-size="14.00">Language experience</text> </g> <!-- nd_2 --> <g id="node3" class="node">
<title>
nd_2
</title>
<path fill="none" stroke="black" d="M315.86,-63C315.86,-63 183.13,-63 183.13,-63 177.13,-63 171.13,-57 171.13,-51 171.13,-51 171.13,-39 171.13,-39 171.13,-33 177.13,-27 183.13,-27 183.13,-27 315.86,-27 315.86,-27 321.86,-27 327.86,-33 327.86,-39 327.86,-39 327.86,-51 327.86,-51 327.86,-57 321.86,-63 315.86,-63"></path> <text text-anchor="middle" x="249.5" y="-40.8" font-family="Times,serif" font-size="14.00">Comprehension outcome</text> </g> <!-- nd_1_l&#45;&gt;nd_2 --> <g id="edge1" class="edge">
<title>
nd_1_l-&gt;nd_2
</title>
<path fill="none" stroke="black" d="M135.37,-61.98C143.77,-60.72 152.47,-59.42 161.13,-58.12"></path> <polygon fill="black" stroke="black" points="161.9,-61.54 171.27,-56.59 160.86,-54.62 161.9,-61.54"></polygon> </g> <!-- nd_1_r --> <g id="node2" class="node">
<title>
nd_1_r
</title>
<path fill="none" stroke="black" d="M118.4,-36C118.4,-36 16.92,-36 16.92,-36 10.92,-36 4.92,-30 4.92,-24 4.92,-24 4.92,-12 4.92,-12 4.92,-6 10.92,0 16.92,0 16.92,0 118.4,0 118.4,0 124.4,0 130.4,-6 130.4,-12 130.4,-12 130.4,-24 130.4,-24 130.4,-30 124.4,-36 118.4,-36"></path> <text text-anchor="middle" x="67.66" y="-13.8" font-family="Times,serif" font-size="14.00">Reasoning capacity</text> </g> <!-- nd_1_r&#45;&gt;nd_2 --> <g id="edge2" class="edge">
<title>
nd_1_r-&gt;nd_2
</title>
<path fill="none" stroke="black" d="M130.3,-27.25C140.24,-28.75 150.69,-30.32 161.1,-31.88"></path> <polygon fill="black" stroke="black" points="160.64,-35.35 171.04,-33.37 161.67,-28.43 160.64,-35.35"></polygon> </g> </g>
</svg>
</div>
<figcaption class="figure-caption">Figure&nbsp;5.3: The potential drivers of comprehension success</figcaption>
</figure>
</div>
</div>
</div>
<!-- ![Freed et al., 2017; structural equation model, adult reading comprehension](freed-2017-fig1-sem-model-1.png){fig-alt="Freed et al., 2017; structural equation model, adult reading comprehension"} -->
</section>
<section id="the-measurement-context-where-the-data-come-from" class="level3" data-number="5.4.9">
<h3 data-number="5.4.9" class="anchored" data-anchor-id="the-measurement-context-where-the-data-come-from"><span class="header-section-number">5.4.9</span> The measurement context: Where the data come from</h3>
<ul>
<li>We measure reading comprehension: asking people to read text and then answer multiple choice questions</li>
<li>We measure background knowledge: vocabulary knowledge (Shipley); health literacy (HLVA)</li>
</ul>
</section>
<section id="reflect-the-kinds-of-critical-evaluation-questions-you-can-ask-yourself" class="level3" data-number="5.4.10">
<h3 data-number="5.4.10" class="anchored" data-anchor-id="reflect-the-kinds-of-critical-evaluation-questions-you-can-ask-yourself"><span class="header-section-number">5.4.10</span> Reflect: The kinds of critical evaluation questions you can ask yourself</h3>
<ul>
<li>Are multiple choice questions good ways to probe understanding? <em>What alternatives are there?</em></li>
<li>Are tests like the Shipley good measures of language knowledge? <em>What do we miss?</em></li>
</ul>
</section>
<section id="reflect-as-we-move-into-thinking-about-the-data-analysis-we-need-to-identify-our-assumptions" class="level3" data-number="5.4.11">
<h3 data-number="5.4.11" class="anchored" data-anchor-id="reflect-as-we-move-into-thinking-about-the-data-analysis-we-need-to-identify-our-assumptions"><span class="header-section-number">5.4.11</span> Reflect: As we move into thinking about the data analysis, we need to identify our assumptions</h3>
<ol type="1">
<li><strong>validity</strong>: that differences in knowledge or ability cause differences in test scores</li>
<li><strong>measurement</strong>: that this is equally true across the different kinds of people we tested</li>
<li><strong>generalizability</strong>: that the sample of people we recruited looks like the population</li>
</ol>
</section>
<section id="we-need-to-think-about-the-derivation-chain" class="level3" data-number="5.4.12">
<h3 data-number="5.4.12" class="anchored" data-anchor-id="we-need-to-think-about-the-derivation-chain"><span class="header-section-number">5.4.12</span> We need to think about the derivation chain</h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-derivation-chain" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<div>
<svg width="672" height="480" viewbox="0.00 0.00 291.19 280.00" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" style="; max-width: none; max-height: none">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 276)">
<title>
Q
</title>
<polygon fill="white" stroke="transparent" points="-4,4 -4,-276 287.19,-276 287.19,4 -4,4"></polygon> <g id="clust1" class="cluster">
<title>
cluster_R
</title>
<polygon fill="none" stroke="black" points="8,-211 8,-264 256,-264 256,-211 8,-211"></polygon> </g> <!-- nd_1_l --> <g id="node1" class="node">
<title>
nd_1_l
</title>
<polygon fill="none" stroke="black" points="16.32,-219.5 16.32,-255.5 137.68,-255.5 137.68,-219.5 16.32,-219.5"></polygon> <text text-anchor="middle" x="77" y="-233.3" font-family="Times,serif" font-size="14.00">Concept formation</text> </g> <!-- nd_1_r --> <g id="node2" class="node">
<title>
nd_1_r
</title>
<polygon fill="none" stroke="black" points="155.7,-219.5 155.7,-255.5 248.3,-255.5 248.3,-219.5 155.7,-219.5"></polygon> <text text-anchor="middle" x="202" y="-233.3" font-family="Times,serif" font-size="14.00">Causal model</text> </g> <!-- nd_2_l --> <g id="node3" class="node">
<title>
nd_2_l
</title>
<polygon fill="none" stroke="black" points="30.9,-146.5 30.9,-182.5 123.1,-182.5 123.1,-146.5 30.9,-146.5"></polygon> <text text-anchor="middle" x="77" y="-160.3" font-family="Times,serif" font-size="14.00">Measurement</text> </g> <!-- nd_1_l&#45;&gt;nd_2_l --> <g id="edge1" class="edge">
<title>
nd_1_l-&gt;nd_2_l
</title>
<path fill="none" stroke="black" d="M77,-219.31C77,-211.29 77,-201.55 77,-192.57"></path> <polygon fill="black" stroke="black" points="80.5,-192.53 77,-182.53 73.5,-192.53 80.5,-192.53"></polygon> </g> <!-- nd_3 --> <g id="node5" class="node">
<title>
nd_3
</title>
<polygon fill="none" stroke="black" points="75.54,-73.5 75.54,-109.5 212.46,-109.5 212.46,-73.5 75.54,-73.5"></polygon> <text text-anchor="middle" x="144" y="-87.3" font-family="Times,serif" font-size="14.00">Statistical predictions</text> </g> <!-- nd_2_l&#45;&gt;nd_3 --> <g id="edge2" class="edge">
<title>
nd_2_l-&gt;nd_3
</title>
<path fill="none" stroke="black" d="M93.22,-146.31C101.53,-137.5 111.8,-126.63 120.92,-116.96"></path> <polygon fill="black" stroke="black" points="123.61,-119.2 127.93,-109.53 118.52,-114.4 123.61,-119.2"></polygon> </g> <!-- nd_2_r --> <g id="node4" class="node">
<title>
nd_2_r
</title>
<polygon fill="none" stroke="black" points="140.81,-146.5 140.81,-182.5 283.19,-182.5 283.19,-146.5 140.81,-146.5"></polygon> <text text-anchor="middle" x="212" y="-160.3" font-family="Times,serif" font-size="14.00">Auxiliary assumptions</text> </g> <!-- nd_2_r&#45;&gt;nd_3 --> <g id="edge4" class="edge">
<title>
nd_2_r-&gt;nd_3
</title>
<path fill="none" stroke="black" d="M195.54,-146.31C187.1,-137.5 176.68,-126.63 167.42,-116.96"></path> <polygon fill="black" stroke="black" points="169.75,-114.33 160.31,-109.53 164.7,-119.17 169.75,-114.33"></polygon> </g> <!-- nd_4 --> <g id="node6" class="node">
<title>
nd_4
</title>
<polygon fill="none" stroke="black" points="82.15,-0.5 82.15,-36.5 205.85,-36.5 205.85,-0.5 82.15,-0.5"></polygon> <text text-anchor="middle" x="144" y="-14.3" font-family="Times,serif" font-size="14.00">Testing hypotheses</text> </g> <!-- nd_3&#45;&gt;nd_4 --> <g id="edge3" class="edge">
<title>
nd_3-&gt;nd_4
</title>
<path fill="none" stroke="black" d="M144,-73.31C144,-65.29 144,-55.55 144,-46.57"></path> <polygon fill="black" stroke="black" points="147.5,-46.53 144,-36.53 140.5,-46.53 147.5,-46.53"></polygon> </g> </g>
</svg>
</div>
<figcaption class="figure-caption">Figure&nbsp;5.4: The derivation chain</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="questions-assumptions-predictions" class="level3" data-number="5.4.13">
<h3 data-number="5.4.13" class="anchored" data-anchor-id="questions-assumptions-predictions"><span class="header-section-number">5.4.13</span> Questions, assumptions, predictions</h3>
<p>Link: concepts, questions <span class="math inline">\(\rightarrow\)</span> assumptions <span class="math inline">\(\rightarrow\)</span> testable predictions</p>
<ol type="1">
<li><strong>concepts, questions</strong>: Can people accurately understand health guidance? <span class="math inline">\(\rightarrow\)</span></li>
<li><strong>assumptions</strong>: People who know more about language should also present more accurate understanding <span class="math inline">\(\rightarrow\)</span></li>
<li><strong>testable predictions</strong>: Higher levels of vocabulary should be associated with higher levels of comprehension accuracy: we expect to estimate a positive coefficient</li>
</ol>
</section>
<section id="one-way-of-thinking-about-the-association-is-to-visualize-it" class="level3" data-number="5.4.14">
<h3 data-number="5.4.14" class="anchored" data-anchor-id="one-way-of-thinking-about-the-association-is-to-visualize-it"><span class="header-section-number">5.4.14</span> One way of thinking about the association is to visualize it</h3>
<ul>
<li>For each value of the predictor <strong>vocabulary</strong></li>
<li>Does the the value of the outcome <strong>accuracy</strong></li>
<li><em>Increase or decrease?</em></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="fig-scatterplot-shipley-acc-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="lm-intro_files/figure-html/fig-scatterplot-shipley-acc-2-1.png" class="img-fluid figure-img" alt="The figure presents a scatterplot indicating the association between variables mean accuracy (on y-axis) and vocabulary (x-axis) scores. The points are shown in grey, and clustered such that higher vocabulary scores tend to be associated with higher accuracy scores. The trend is indicated by a thick red line." width="480"></p>
<figcaption class="figure-caption">Figure&nbsp;5.5: The association between comprehension accuracy and vocabulary</figcaption>
</figure>
</div>
</div>
</div>
<!-- gelman -- p.4 -- Regression is a method that allows researchers to summarize how predictions or average values of an outcome vary across individuals defined by a set of predictors. -->
<!-- -- consolidate -- the linear model with one predictor -->
<!-- -- explain -- the linear model as a prediction engine -->
<!-- -- explain -- differences in average outcomes given differences in groups or continuous variables -->
<!-- -- demonstrate -- the construction of the prediction line -->
<!-- -- explain -- the linear sum of terms -->
<!-- -- explain -- the best fit line -- residuals -->
</section>
<section id="predicted-association-as-expected-change-in-average-outcome" class="level3" data-number="5.4.15">
<h3 data-number="5.4.15" class="anchored" data-anchor-id="predicted-association-as-expected-change-in-average-outcome"><span class="header-section-number">5.4.15</span> Predicted association as <em>expected</em> change in average outcome</h3>
<ul>
<li><a href="#fig-scatterplot-ridges-shipley-acc-1">Figure&nbsp;<span>5.6</span></a> shows the distribution curve of mean (comprehension) accuracy scores observed at each value of vocabulary</li>
<li>You can see that the middle – the average – of each distribution increases</li>
<li>as we go from left (low scores) to right (high scores) on vocabulary</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="fig-scatterplot-ridges-shipley-acc-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="lm-intro_files/figure-html/fig-scatterplot-ridges-shipley-acc-1-1.png" class="img-fluid figure-img" alt="The figure presents a indicating the association between variables mean accuracy (on y-axis) and vocabulary (x-axis) scores. In the plot, the points are shown in dark red and clustered such that higher vocabulary scores tend to be associated with higher accuracy scores. Ridges are superimposed on the points, shown in dark grey and red. We show the distribution curve of mean (comprehension) accuracy scores observed at each value of vocabulary. You can see that the middle -- the average -- of each distribution increases as we go from left (low scores) to right (high scores)." width="576"></p>
<figcaption class="figure-caption">Figure&nbsp;5.6: Association between accuracy and vocabulary</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="how-do-we-estimate-the-association-between-two-variables" class="level3" data-number="5.4.16">
<h3 data-number="5.4.16" class="anchored" data-anchor-id="how-do-we-estimate-the-association-between-two-variables"><span class="header-section-number">5.4.16</span> How do we <em>estimate</em> the association between two variables?</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> SHIPLEY,</span>
<span id="cb1-2"><a href="#cb1-2"></a>            <span class="at">data =</span> clearly.one.subjects)</span>
<span id="cb1-3"><a href="#cb1-3"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol type="1">
<li>Specify the <code>lm</code> function and the model <code>mean.acc ~ SHIPLEY</code></li>
<li>Specify what data we use <code>data = clearly.one.subjects</code></li>
<li>Get the results <code>summary(model)</code></li>
</ol>
</section>
<section id="the-sentence-structure-of-models-in-r" class="level3" data-number="5.4.17">
<h3 data-number="5.4.17" class="anchored" data-anchor-id="the-sentence-structure-of-models-in-r"><span class="header-section-number">5.4.17</span> The sentence structure of models in R</h3>
<p>Take a good look:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(mean.acc <span class="sc">~</span> SHIPLEY ...)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You will see this sentence structure in coding for <em>many</em> different analysis types</p>
<ul>
<li><code>method(outcome ~ predictors)</code></li>
<li><code>method</code> could be <code>aov, brm, lm, glm, glmm, lmer, t.test, cor.test</code></li>
</ul>
</section>
<section id="results-how-does-the-outcome-vary-in-relation-to-the-predictor" class="level3 smaller" data-number="5.4.18">
<h3 class="smaller anchored" data-number="5.4.18" data-anchor-id="results-how-does-the-outcome-vary-in-relation-to-the-predictor"><span class="header-section-number">5.4.18</span> Results: How does the outcome vary in relation to the predictor?</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> SHIPLEY,</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> clearly.one.subjects)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ SHIPLEY, data = clearly.one.subjects)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.42871 -0.04921  0.02079  0.07480  0.18430 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.44914    0.08053   5.577 9.67e-08 ***
SHIPLEY      0.01050    0.00229   4.585 8.85e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1115 on 167 degrees of freedom
Multiple R-squared:  0.1118,    Adjusted R-squared:  0.1065 
F-statistic: 21.03 on 1 and 167 DF,  p-value: 8.846e-06</code></pre>
</div>
</div>
<ul>
<li>A model summary gives us estimates of:</li>
<li>The coefficient <span class="math inline">\(= 0.44914\)</span> for the intercept</li>
<li>The coefficient <span class="math inline">\(= 0.01050\)</span> for the slope of the SHIPLEY ‘effect’</li>
</ul>
</section>
<section id="these-coefficients-build-a-line" class="level3" data-number="5.4.19">
<h3 data-number="5.4.19" class="anchored" data-anchor-id="these-coefficients-build-a-line"><span class="header-section-number">5.4.19</span> These <em>coefficients</em> build a line</h3>
<ul>
<li>The line represents:</li>
<li>our prediction for how the outcome varies <em>on average</em></li>
<li>given change in the predictor</li>
</ul>
</section>
<section id="so-now-we-need-to-think-about-straight-lines" class="level3" data-number="5.4.20">
<h3 data-number="5.4.20" class="anchored" data-anchor-id="so-now-we-need-to-think-about-straight-lines"><span class="header-section-number">5.4.20</span> So now we need to think about straight lines</h3>
<!-- -- gelman2021 p.37 -->
<ol type="1">
<li>You may remember from school that to draw a straight line you need four numbers:</li>
</ol>
<p><span class="math display">\[y = a + bx\]</span></p>
<ol start="2" type="1">
<li>We calculate the height <span class="math inline">\(y\)</span> by adding</li>
</ol>
<ul>
<li><span class="math inline">\(a\)</span> the intercept, the value of y when <span class="math inline">\(x = 0\)</span></li>
<li>to the product of <span class="math inline">\(b\)</span> the coefficient for the slope of the line</li>
<li>multiplied by <span class="math inline">\(x\)</span> the value of the predictor variable</li>
</ul>
</section>
<section id="lets-draw-it" class="level3" data-number="5.4.21">
<h3 data-number="5.4.21" class="anchored" data-anchor-id="lets-draw-it"><span class="header-section-number">5.4.21</span> Let’s draw it</h3>
<!-- -- gelman2021 p.37 -->
<ul>
<li>Look at what we get if we draw the line using the linear model coefficients:</li>
<li><span class="math inline">\(= 0.449\)</span> for the intercept, <span class="math inline">\(a\)</span></li>
<li><span class="math inline">\(= 0.011\)</span> for the slope, <span class="math inline">\(b\)</span></li>
<li>In the formula: <span class="math inline">\(y = 0.449 + 0.011x\)</span></li>
<li>(I round the numbers to three decimal places.)</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="fig-prediction-shipley-acc-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="lm-intro_files/figure-html/fig-prediction-shipley-acc-1-1.png" class="img-fluid figure-img" alt="The figure presents a line indicating the predicted association between variables mean accuracy (on y-axis) and vocabulary (x-axis) scores. In the plot, higher vocabulary scores are predicted to be associated with higher accuracy scores. Model prediction of change in outcome is shown with a red line." width="480"></p>
<figcaption class="figure-caption">Figure&nbsp;5.7: The <em>predicted</em> association between comprehension accuracy and vocabulary</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="we-can-understand-the-line-as-representing-a-set-of-predictions" class="level3" data-number="5.4.22">
<h3 data-number="5.4.22" class="anchored" data-anchor-id="we-can-understand-the-line-as-representing-a-set-of-predictions"><span class="header-section-number">5.4.22</span> We can understand the line as representing a set of predictions</h3>
<!-- -- gelman2021 p.37 -->
<ul>
<li>To see how — we use the coefficients to predict just one potential outcome:</li>
<li>the expected accuracy for someone with a vocabulary score of 20</li>
<li>We do this using the formula:</li>
</ul>
<p><span class="math inline">\(\text{predicted y} = 0.449 + \text{0.011 } \times \text{ Shipley score of } 20\)</span></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-prediction-shipley-acc-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="lm-intro_files/figure-html/fig-prediction-shipley-acc-2-1.png" class="img-fluid figure-img" alt="The figure presents a scatterplot indicating the association between variables mean accuracy (on y-axis) and vocabulary (x-axis) scores. The points are shown in grey, and clustered such that higher vocabulary scores tend to be associated with higher accuracy scores. We predict the value of comprehension accuracy given a Shipley vocabulary score of 20: the point is shown in red at about mean accuracy of 65." width="480"></p>
<figcaption class="figure-caption">Figure&nbsp;5.8: Predicted outcome in red</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="we-can-understand-the-line-as-representing-a-set-of-predictions-1" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="we-can-understand-the-line-as-representing-a-set-of-predictions-1"><span class="header-section-number">5.5</span> We can understand the line as representing a set of predictions</h2>
<!-- -- gelman2021 p.37 -->
<ul>
<li>Let’s expand our predictions</li>
</ul>
<ol type="1">
<li>Predict accuracy given a Shipley score of 20</li>
</ol>
<ul>
<li><span class="math inline">\(y = 0.449 + 0.011 \times 20\)</span></li>
</ul>
<ol start="2" type="1">
<li>Predict accuracy given a Shipley score of 30</li>
</ol>
<ul>
<li><span class="math inline">\(y = 0.449 + 0.011 \times 30\)</span></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="fig-prediction-shipley-acc-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="lm-intro_files/figure-html/fig-prediction-shipley-acc-3-1.png" class="img-fluid figure-img" alt="The figure presents a scatterplot indicating the association between variables mean accuracy (on y-axis) and vocabulary (x-axis) scores. The points are shown in grey, and clustered such that higher vocabulary scores tend to be associated with higher accuracy scores. We predict the value of comprehension accuracy given Shipley vocabulary scoreS of 20 and 30." width="480"></p>
<figcaption class="figure-caption">Figure&nbsp;5.9: Predicted outcome in red</figcaption>
</figure>
</div>
</div>
</div>
<section id="the-linear-model-allows-us-to-predict-the-average-outcome-we-can-expect-given-any-value-of-the-predictor" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="the-linear-model-allows-us-to-predict-the-average-outcome-we-can-expect-given-any-value-of-the-predictor"><span class="header-section-number">5.5.1</span> The linear model allows us to predict the average outcome we can expect given <em>any</em> value of the predictor</h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-prediction-shipley-acc-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="lm-intro_files/figure-html/fig-prediction-shipley-acc-4-1.png" class="img-fluid figure-img" alt="The figure presents a scatterplot indicating the association between variables mean accuracy (on y-axis) and vocabulary (x-axis) scores. The points are shown in grey, and clustered such that higher vocabulary scores tend to be associated with higher accuracy scores. We predict the value of comprehension accuracy given Shipley vocabulary scoreS of 20 and 30. A blue line is drawn through the linear model predicted trend." width="480"></p>
<figcaption class="figure-caption">Figure&nbsp;5.10: The predicted change in mean comprehension accuracy, given variation in vocabulary scores</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="we-could-draw-a-variety-of-different-model-prediction-lines-how-do-we-pick-the-right-one" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="we-could-draw-a-variety-of-different-model-prediction-lines-how-do-we-pick-the-right-one"><span class="header-section-number">5.5.2</span> We could draw a variety of different model prediction lines: how do we pick the <em>right</em> one?</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="lm-intro_files/figure-html/abline-predict-random-2-1.png" class="img-fluid figure-img" alt="The figure presents a scatterplot indicating the association between variables mean accuracy (on y-axis) and vocabulary (x-axis) scores. The points are shown in grey, and clustered such that higher vocabulary scores tend to be associated with higher accuracy scores. The trend is indicated by a thick red line. In the background, a fan of light pink lines indicate possible ways to capture the trend of the association." width="480"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="we-could-draw-a-variety-of-different-model-prediction-lines-how-do-we-pick-the-right-one-1" class="level3" data-number="5.5.3">
<h3 data-number="5.5.3" class="anchored" data-anchor-id="we-could-draw-a-variety-of-different-model-prediction-lines-how-do-we-pick-the-right-one-1"><span class="header-section-number">5.5.3</span> We could draw a variety of different model prediction lines: how do we pick the <em>right</em> one?</h3>
<p>We need to go back to the prediction model</p>
<ul>
<li>To calculate a predicted outcome value, we calculated it as: <span class="math inline">\(\text{predicted y} = 0.449 + 0.011 \times \text{ Shipley score } 20\)</span></li>
<li>Assuming the linear model <span class="math inline">\(\text{predicted y} = intercept + \text{slope } \times \text{ vocabulary}\)</span></li>
<li>But we missed a bit: <strong>error</strong></li>
</ul>
</section>
<section id="linear-models-are-typically-estimated-given-sample-data" class="level3" data-number="5.5.4">
<h3 data-number="5.5.4" class="anchored" data-anchor-id="linear-models-are-typically-estimated-given-sample-data"><span class="header-section-number">5.5.4</span> Linear models are typically estimated given sample data</h3>
<ul>
<li>Maybe you noticed that I talked about how the model allows us to predict</li>
<li>how the outcome varies <strong>on average</strong> given different values of the predictor</li>
<li>When we use a linear model to estimate the intercept and slope – to build the predictions – we fit a model to the sample data</li>
<li>And no model will fit sample data perfectly</li>
</ul>
<!-- -- gelman -- p.103 -- given more than two data points, cannot find a line that gives a perfect fit -->
</section>
<section id="linear-models-are-typically-estimated-given-sample-data-1" class="level3" data-number="5.5.5">
<h3 data-number="5.5.5" class="anchored" data-anchor-id="linear-models-are-typically-estimated-given-sample-data-1"><span class="header-section-number">5.5.5</span> Linear models are typically estimated given sample data</h3>
<!-- -- gelman -- p.49 -- measurement error model -->
<p>Usually, this means there are differences between the expected outcomes that the model predicts and the observed outcomes</p>
<ul>
<li>So we often write the linear model like this: <span class="math inline">\(y = a + bx + \epsilon\)</span></li>
</ul>
<ol type="1">
<li>The observed outcome <span class="math inline">\(y\)</span> equals</li>
<li>the intercept <span class="math inline">\(a\)</span></li>
<li>plus the difference associated with a specific predictor value <span class="math inline">\(bx\)</span></li>
<li>plus some amount of mismatch or error <span class="math inline">\(\epsilon\)</span>, the difference between the observed outcome and the predicted outcome</li>
</ol>
</section>
<section id="we-can-derive-the-formulas-used-to-calculate-the-estimates-using-calculus" class="level3" data-number="5.5.6">
<h3 data-number="5.5.6" class="anchored" data-anchor-id="we-can-derive-the-formulas-used-to-calculate-the-estimates-using-calculus"><span class="header-section-number">5.5.6</span> We can derive the formulas used to calculate the estimates using calculus</h3>
<ul>
<li>But we won’t</li>
<li>Because the linear model calculations are done using matrix solution algorithms in R <em>so we don’t have to</em> <!-- -- gelman -- p.104 --></li>
</ul>
</section>
<section id="what-do-the-prediction-errors-the-residuals-look-like" class="level3" data-number="5.5.7">
<h3 data-number="5.5.7" class="anchored" data-anchor-id="what-do-the-prediction-errors-the-residuals-look-like"><span class="header-section-number">5.5.7</span> What do the prediction errors – the residuals – look like?</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-abline-predict-residuals-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="lm-intro_files/figure-html/fig-abline-predict-residuals-1-1.png" class="img-fluid figure-img" alt="The figure presents a scatterplot indicating the association between variables mean accuracy (on y-axis) and vocabulary (x-axis) scores. The points are shown in different shades of orange to red, and clustered such that higher vocabulary scores tend to be associated with higher accuracy scores. The predicted trend is indicated by a thick blue line. Predicted outcomes, given different sample values of vocabulary are circled in black along the blue line. Light grey lines indicate the difference between predicted and observed outcomes. The observed points are darker red the further they are from the prediction." width="480"></p>
<figcaption class="figure-caption">Figure&nbsp;5.11: The predicted change in mean comprehension accuracy, given variation in vocabulary scores. Observed values are shown in orange-red. Predicted values are shown in blue</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="what-the-prediction-errors-look-like" class="level3" data-number="5.5.8">
<h3 data-number="5.5.8" class="anchored" data-anchor-id="what-the-prediction-errors-look-like"><span class="header-section-number">5.5.8</span> What the prediction errors look like</h3>
<ul>
<li>The model expectation: higher vocabulary predicts higher mean comprehension accuracy</li>
<li>The predicted points are shown by the blue line</li>
<li>The prediction line increases in height for higher values of vocabulary</li>
<li>Look at the <strong>differences in height</strong> between the observed points (in orange-red) and predicted points</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-abline-predict-residuals-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="lm-intro_files/figure-html/fig-abline-predict-residuals-2-1.png" class="img-fluid figure-img" alt="The figure presents a scatterplot indicating the association between variables mean accuracy (on y-axis) and vocabulary (x-axis) scores. The points are shown in different shades of orange to red, and clustered such that higher vocabulary scores tend to be associated with higher accuracy scores. The predicted trend is indicated by a thick blue line. Predicted outcomes, given different sample values of vocabulary are circled in black along the blue line. Light grey lines indicate the difference between predicted and observed outcomes. The observed points are darker red the further they are from the prediction." width="480"></p>
<figcaption class="figure-caption">Figure&nbsp;5.12: The predicted change in mean comprehension accuracy, given variation in vocabulary scores. Observed values are shown in orange-red. Predicted values are shown in blue</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="what-the-prediction-errors-look-like-1" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="what-the-prediction-errors-look-like-1"><span class="header-section-number">5.6</span> What the prediction errors look like</h2>
<ul>
<li>If the regression model were perfect then all the observed points would lie on the prediction line</li>
<li>They do not</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-abline-predict-residuals-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="lm-intro_files/figure-html/fig-abline-predict-residuals-3-1.png" class="img-fluid figure-img" alt="The figure presents a scatterplot indicating the association between variables mean accuracy (on y-axis) and vocabulary (x-axis) scores. The points are shown in different shades of orange to red, and clustered such that higher vocabulary scores tend to be associated with higher accuracy scores. The predicted trend is indicated by a thick blue line. Predicted outcomes, given different sample values of vocabulary are circled in black along the blue line. Light grey lines indicate the difference between predicted and observed outcomes. The observed points are darker red the further they are from the prediction." width="480"></p>
<figcaption class="figure-caption">Figure&nbsp;5.13: The predicted change in mean comprehension accuracy, given variation in vocabulary scores. Observed values are shown in orange-red. Predicted values are shown in blue</figcaption>
</figure>
</div>
</div>
</div>
<section id="what-the-prediction-errors-look-like-2" class="level3" data-number="5.6.1">
<h3 data-number="5.6.1" class="anchored" data-anchor-id="what-the-prediction-errors-look-like-2"><span class="header-section-number">5.6.1</span> What the prediction errors look like</h3>
<ul>
<li>Differences between observed and predicted outcomes are shown by the vertical lines</li>
<li>Better models should show smaller differences between observed and predicted outcome values</li>
<li>Notice: some participants had same vocabulary scores but different outcomes</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-abline-predict-residuals-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="lm-intro_files/figure-html/fig-abline-predict-residuals-4-1.png" class="img-fluid figure-img" alt="The figure presents a scatterplot indicating the association between variables mean accuracy (on y-axis) and vocabulary (x-axis) scores. The points are shown in different shades of orange to red, and clustered such that higher vocabulary scores tend to be associated with higher accuracy scores. The predicted trend is indicated by a thick blue line. Predicted outcomes, given different sample values of vocabulary are circled in black along the blue line. Light grey lines indicate the difference between predicted and observed outcomes. The observed points are darker red the further they are from the prediction." width="480"></p>
<figcaption class="figure-caption">Figure&nbsp;5.14: The predicted change in mean comprehension accuracy, given variation in vocabulary scores. Observed values are shown in orange-red. Predicted values are shown in blue</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="we-typically-assume-that-the-residuals-are-normally-distributed" class="level3" data-number="5.6.2">
<h3 data-number="5.6.2" class="anchored" data-anchor-id="we-typically-assume-that-the-residuals-are-normally-distributed"><span class="header-section-number">5.6.2</span> We typically assume that the residuals are normally distributed</h3>
<ul>
<li>Some are positive: observed outcome larger than predicted outcome</li>
<li>Some are negative: observed outcome smaller than predicted outcome</li>
<li>The average of the residuals will be zero overall</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-residuals-density-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="lm-intro_files/figure-html/fig-residuals-density-1-1.png" class="img-fluid figure-img" alt="The figure a histogram of the residuals, the prediction errors, for the linear model of the association between mean comprehension accuracy and vocabulary. The histogram is shown in grey, and the peak is centered at residuals = 0. A dashed red line is drawn at resdiduals = 0. A red density curve is superimposed on the histogram to indicate the theoretical normal distribution of residuals." width="480"></p>
<figcaption class="figure-caption">Figure&nbsp;5.15: Plot showing the distribution of prediction errors – residuals – for the linear model of comprehension accuracy</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="so-we-pick-the-line-that-minimizes-the-residuals-the-mismatch-between-predicted-and-observed-outcomes" class="level3" data-number="5.6.3">
<h3 data-number="5.6.3" class="anchored" data-anchor-id="so-we-pick-the-line-that-minimizes-the-residuals-the-mismatch-between-predicted-and-observed-outcomes"><span class="header-section-number">5.6.3</span> So: We pick the line that minimizes the residuals – the mismatch between predicted and observed outcomes</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="lm-intro_files/figure-html/abline-predict-random-3-1.png" class="img-fluid figure-img" alt="The figure presents a scatterplot indicating the association between variables mean accuracy (on y-axis) and vocabulary (x-axis) scores. The points are shown in grey, and clustered such that higher vocabulary scores tend to be associated with higher accuracy scores. The trend is indicated by a thick red line. In the background, a fan of light pink lines indicate possible ways to capture the trend of the association." width="480"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="identifying-the-key-information-in-the-linear-model-results" class="level3" data-number="5.6.4">
<h3 data-number="5.6.4" class="anchored" data-anchor-id="identifying-the-key-information-in-the-linear-model-results"><span class="header-section-number">5.6.4</span> Identifying the key information in the linear model results</h3>
<ul>
<li>The <code>summary()</code> of the linear model shows …</li>
<li>The <code>Estimate</code> of the <code>Coefficient</code> of the effect of individual differences in vocabulary (<code>SHIPLEY</code>)</li>
<li>how much the outcome <code>mean.acc</code> value changes, given differences in <code>SHIPLEY</code> score</li>
<li>Associated <code>t value</code> and <code>Pr(&gt; |t|)</code> statistics for the coefficient t-test</li>
<li>Model fit statistics: <code>R-squared</code> and <code>F-statistic</code></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> SHIPLEY, <span class="at">data =</span> clearly.one.subjects)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ SHIPLEY, data = clearly.one.subjects)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.42871 -0.04921  0.02079  0.07480  0.18430 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.44914    0.08053   5.577 9.67e-08 ***
SHIPLEY      0.01050    0.00229   4.585 8.85e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1115 on 167 degrees of freedom
Multiple R-squared:  0.1118,    Adjusted R-squared:  0.1065 
F-statistic: 21.03 on 1 and 167 DF,  p-value: 8.846e-06</code></pre>
</div>
</div>
</section>
<section id="for-the-effect-of-vocabulary-shipley-we-have" class="level3" data-number="5.6.5">
<h3 data-number="5.6.5" class="anchored" data-anchor-id="for-the-effect-of-vocabulary-shipley-we-have"><span class="header-section-number">5.6.5</span> For the effect of vocabulary (SHIPLEY), we have:</h3>
<ul>
<li>The coefficient for the slope of the effect of variation in vocabulary scores: <code>0.01050</code></li>
<li>The <code>Std. Error</code> (standard error) <code>0.00229</code> for that estimate</li>
<li>The <code>t</code>value <code>4.585</code> and associated <code>Pr(&gt;|t|)</code> p-value <code>8.85e-06</code> for the null hypothesis test of the coefficient</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> SHIPLEY, <span class="at">data =</span> clearly.one.subjects)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ SHIPLEY, data = clearly.one.subjects)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.42871 -0.04921  0.02079  0.07480  0.18430 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.44914    0.08053   5.577 9.67e-08 ***
SHIPLEY      0.01050    0.00229   4.585 8.85e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1115 on 167 degrees of freedom
Multiple R-squared:  0.1118,    Adjusted R-squared:  0.1065 
F-statistic: 21.03 on 1 and 167 DF,  p-value: 8.846e-06</code></pre>
</div>
</div>
</section>
<section id="identifying-the-key-information-in-the-results" class="level3" data-number="5.6.6">
<h3 data-number="5.6.6" class="anchored" data-anchor-id="identifying-the-key-information-in-the-results"><span class="header-section-number">5.6.6</span> Identifying the key information in the results</h3>
<ul>
<li>Pay attention to the <strong>sign and the size</strong> of the coefficient estimate:</li>
<li>Is the coefficient (e.g., SHIPLEY <code>0.01050</code>) a positive or a negative number?</li>
<li>Is it relatively large or small?</li>
<li>We come back to this, shortly, in the context of interpretation and reporting</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> SHIPLEY, <span class="at">data =</span> clearly.one.subjects)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ SHIPLEY, data = clearly.one.subjects)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.42871 -0.04921  0.02079  0.07480  0.18430 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.44914    0.08053   5.577 9.67e-08 ***
SHIPLEY      0.01050    0.00229   4.585 8.85e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1115 on 167 degrees of freedom
Multiple R-squared:  0.1118,    Adjusted R-squared:  0.1065 
F-statistic: 21.03 on 1 and 167 DF,  p-value: 8.846e-06</code></pre>
</div>
</div>
</section>
<section id="the-t-tests-in-the-linear-model" class="level3" data-number="5.6.7">
<h3 data-number="5.6.7" class="anchored" data-anchor-id="the-t-tests-in-the-linear-model"><span class="header-section-number">5.6.7</span> The t-tests in the linear model</h3>
<!-- -- gelman -- p.147 -->
<!-- -- howell -- p.261, 275 pp.543-545 -->
<!-- -- cohen -- p.86 -->
<p><span class="math display">\[t = \frac{\beta_j}{s_{\beta_j}}\]</span></p>
<!-- - We follow statistical convention and refer to the coefficient estimate as $\beta_j$ (b) -->
<ul>
<li>For each coefficient, the t-test is used to evaluate if the coefficient <span class="math inline">\(\beta_j\)</span> is significantly different from zero</li>
<li>We assume the <strong>null hypothesis</strong> that the coefficient <span class="math inline">\(\beta_j\)</span> is zero</li>
<li>We do the test by comparing the estimated coefficient <span class="math inline">\(\beta_j\)</span> with the standard error of the estimate</li>
</ul>
</section>
<section id="the-t-tests-in-the-linear-model-1" class="level3" data-number="5.6.8">
<h3 data-number="5.6.8" class="anchored" data-anchor-id="the-t-tests-in-the-linear-model-1"><span class="header-section-number">5.6.8</span> The t-tests in the linear model</h3>
<!-- -- gelman -- p.147 -->
<!-- -- howell -- p.261, 275 pp.543-545 -->
<!-- -- cohen -- p.86 -->
<p><span class="math display">\[t = \frac{\beta_j}{s_{\beta_j}}\]</span></p>
<ul>
<li>The standard error <span class="math inline">\(s_{\beta_j}\)</span> indicates our <strong>uncertainty</strong> about the estimate</li>
<li>Larger standard errors represent greater uncertainty</li>
</ul>
</section>
<section id="the-t-tests-in-the-linear-model-2" class="level3" data-number="5.6.9">
<h3 data-number="5.6.9" class="anchored" data-anchor-id="the-t-tests-in-the-linear-model-2"><span class="header-section-number">5.6.9</span> The t-tests in the linear model</h3>
<!-- -- gelman -- p.147 -->
<!-- -- howell -- p.261, 275 pp.543-545 -->
<!-- -- cohen -- p.86 -->
<p><span class="math display">\[t = \frac{\beta_j}{s_{\beta_j}}\]</span></p>
<ul>
<li>Standard errors can be calculated using information about:</li>
<li>Error in the model — think of the distribution of residuals</li>
<li>Variation of values in the predictor — how widely they range</li>
<li>The sample size</li>
<li>Standard errors will be smaller for the coefficients of effects that appear to have bigger impacts, in models that describe outcomes better, in larger samples</li>
</ul>
</section>
<section id="identifying-the-key-information-in-the-results-1" class="level3 smaller" data-number="5.6.10">
<h3 class="smaller anchored" data-number="5.6.10" data-anchor-id="identifying-the-key-information-in-the-results-1"><span class="header-section-number">5.6.10</span> Identifying the key information in the results</h3>
<ul>
<li>Pay attention to R-squared:</li>
<li>The model summary gives us the <code>Multiple R-squared</code> and <code>Adjusted R-squared</code></li>
<li>These numbers represent how much of the variation in the outcome can be predicted by the model</li>
<li>We usually report <code>Adjusted R-squared</code> because it tends to be more accurate</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> SHIPLEY, <span class="at">data =</span> clearly.one.subjects)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ SHIPLEY, data = clearly.one.subjects)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.42871 -0.04921  0.02079  0.07480  0.18430 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.44914    0.08053   5.577 9.67e-08 ***
SHIPLEY      0.01050    0.00229   4.585 8.85e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1115 on 167 degrees of freedom
Multiple R-squared:  0.1118,    Adjusted R-squared:  0.1065 
F-statistic: 21.03 on 1 and 167 DF,  p-value: 8.846e-06</code></pre>
</div>
</div>
</section>
<section id="r-squared-what-is-it-an-indicator-of-the-proportion-of-outcome-variation-we-can-predict" class="level3" data-number="5.6.11">
<h3 data-number="5.6.11" class="anchored" data-anchor-id="r-squared-what-is-it-an-indicator-of-the-proportion-of-outcome-variation-we-can-predict"><span class="header-section-number">5.6.11</span> R-squared – what is it? – an indicator of the proportion of outcome variation we can predict</h3>
<ul>
<li>Better models should show smaller differences between observed and predicted outcomes</li>
<li>R-squared (<span class="math inline">\(R^2\)</span>) gives the proportion of outcome variance</li>
<li>we can predict given information about differences in vocabulary</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-abline-predict-residuals-5" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="lm-intro_files/figure-html/fig-abline-predict-residuals-5-1.png" class="img-fluid figure-img" alt="The figure presents a scatterplot indicating the association between variables mean accuracy (on y-axis) and vocabulary (x-axis) scores. The points are shown in different shades of orange to red, and clustered such that higher vocabulary scores tend to be associated with higher accuracy scores. The predicted trend is indicated by a thick blue line. Predicted outcomes, given different sample values of vocabulary are circled in black along the blue line. Light grey lines indicate the difference between predicted and observed outcomes. The observed points are darker red the further they are from the prediction." width="480"></p>
<figcaption class="figure-caption">Figure&nbsp;5.16: The difference between predicted and observed outcomes, given variation in vocabulary</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="r-squared-as-an-indicator-of-the-proportion-of-the-outcome-variation-we-can-predict" class="level3 smaller" data-number="5.6.12">
<h3 class="smaller anchored" data-number="5.6.12" data-anchor-id="r-squared-as-an-indicator-of-the-proportion-of-the-outcome-variation-we-can-predict"><span class="header-section-number">5.6.12</span> R-squared as an indicator of the proportion of the outcome variation we can predict</h3>
<ul>
<li>To understand what this means, look at the scatterplot</li>
<li>On average, values in outcome (accuracy) increase with increasing values in the predictor (vocabulary)</li>
<li>But different people got different outcomes even with same vocabulary scores</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-abline-predict-residuals-6" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="lm-intro_files/figure-html/fig-abline-predict-residuals-6-1.png" class="img-fluid figure-img" alt="The figure presents a scatterplot indicating the association between variables mean accuracy (on y-axis) and vocabulary (x-axis) scores. The points are shown in different shades of orange to red, and clustered such that higher vocabulary scores tend to be associated with higher accuracy scores. The predicted trend is indicated by a thick blue line. Predicted outcomes, given different sample values of vocabulary are circled in black along the blue line. Light grey lines indicate the difference between predicted and observed outcomes. The observed points are darker red the further they are from the prediction." width="480"></p>
<figcaption class="figure-caption">Figure&nbsp;5.17: The difference between predicted and observed outcomes, given variation in vocabulary</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="r-squared-as-an-indicator-of-the-proportion-of-the-outcome-variation-we-can-predict-1" class="level3 smaller" data-number="5.6.13">
<h3 class="smaller anchored" data-number="5.6.13" data-anchor-id="r-squared-as-an-indicator-of-the-proportion-of-the-outcome-variation-we-can-predict-1"><span class="header-section-number">5.6.13</span> R-squared as an indicator of the proportion of the outcome variation we can predict</h3>
<ul>
<li>So: we have variation in the outcome that is related to variation in the predictor</li>
<li>And: we have variation in the outcome that seems unrelated to the predictor</li>
<li><span class="math inline">\(R^2\)</span> tells us how much variation in the outcome is explained by the model</li>
<li><span class="math inline">\(R^2\)</span> gives us a proportion where <span class="math inline">\(R^2 = \frac{\text{predicted outcome variation}}{\text{total outcome variation}}\)</span></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-abline-predict-residuals-7" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="lm-intro_files/figure-html/fig-abline-predict-residuals-7-1.png" class="img-fluid figure-img" alt="The figure presents a scatterplot indicating the association between variables mean accuracy (on y-axis) and vocabulary (x-axis) scores. The points are shown in different shades of orange to red, and clustered such that higher vocabulary scores tend to be associated with higher accuracy scores. The predicted trend is indicated by a thick blue line. Predicted outcomes, given different sample values of vocabulary are circled in black along the blue line. Light grey lines indicate the difference between predicted and observed outcomes. The observed points are darker red the further they are from the prediction." width="480"></p>
<figcaption class="figure-caption">Figure&nbsp;5.18: The difference between predicted and observed outcomes, given variation in vocabulary</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="identifying-the-key-information-in-the-results-2" class="level3" data-number="5.6.14">
<h3 data-number="5.6.14" class="anchored" data-anchor-id="identifying-the-key-information-in-the-results-2"><span class="header-section-number">5.6.14</span> Identifying the key information in the results</h3>
<ul>
<li>Pay attention to F:</li>
<li>The model summary gives us the F-statistic:</li>
<li>This is the test statistic for the test of the null hypothesis that the model does not predict the outcome</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> SHIPLEY, <span class="at">data =</span> clearly.one.subjects)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ SHIPLEY, data = clearly.one.subjects)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.42871 -0.04921  0.02079  0.07480  0.18430 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.44914    0.08053   5.577 9.67e-08 ***
SHIPLEY      0.01050    0.00229   4.585 8.85e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1115 on 167 degrees of freedom
Multiple R-squared:  0.1118,    Adjusted R-squared:  0.1065 
F-statistic: 21.03 on 1 and 167 DF,  p-value: 8.846e-06</code></pre>
</div>
</div>
</section>
<section id="reporting-the-results-of-a-linear-model" class="level3" data-number="5.6.15">
<h3 data-number="5.6.15" class="anchored" data-anchor-id="reporting-the-results-of-a-linear-model"><span class="header-section-number">5.6.15</span> Reporting the results of a linear model</h3>
<ul>
<li>You will need to report three bits of information:</li>
</ul>
<ol type="1">
<li><span class="math inline">\(R^2\)</span> how much outcome variation is explained by the model</li>
<li><span class="math inline">\(F\)</span> test for the null hypothesis that none of the predictors actually predict the outcome</li>
<li>Coefficient estimates with the t-tests for the null hypothesis for each coefficient</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> SHIPLEY, <span class="at">data =</span> clearly.one.subjects)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ SHIPLEY, data = clearly.one.subjects)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.42871 -0.04921  0.02079  0.07480  0.18430 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.44914    0.08053   5.577 9.67e-08 ***
SHIPLEY      0.01050    0.00229   4.585 8.85e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1115 on 167 degrees of freedom
Multiple R-squared:  0.1118,    Adjusted R-squared:  0.1065 
F-statistic: 21.03 on 1 and 167 DF,  p-value: 8.846e-06</code></pre>
</div>
</div>
</section>
<section id="the-language-and-style-of-reporting-linear-model-results" class="level3" data-number="5.6.16">
<h3 data-number="5.6.16" class="anchored" data-anchor-id="the-language-and-style-of-reporting-linear-model-results"><span class="header-section-number">5.6.16</span> The language and style of reporting linear model results</h3>
<p>Here is an example of results reporting text that is conventional:</p>
<blockquote class="blockquote">
<p>We fitted a linear model with mean comprehension accuracy as the outcome and vocabulary (Shipley) as the predictor. Our analysis indicated a significant effect of vocabulary knowledge. The model is significant overall, with <span class="math inline">\(F(1, 167) = 21.03, p &lt; .001\)</span>, and explains 11% of variance (<span class="math inline">\(\text{adjusted } R^2 = 0.11\)</span>). The model estimates showed that the accuracy of comprehension increased with increasing levels of participant vocabulary knowledge (<span class="math inline">\(\beta = .011, t = 4.59, p &lt;.001\)</span>).</p>
</blockquote>
</section>
<section id="look-at-what-we-do-with-the-text" class="level3" data-number="5.6.17">
<h3 data-number="5.6.17" class="anchored" data-anchor-id="look-at-what-we-do-with-the-text"><span class="header-section-number">5.6.17</span> Look at what we do with the text</h3>
<ol type="1">
<li>Explain what I did, specifying the method (linear model), the outcome variable (accuracy) and the predictor variables (health literacy, reading strategy, reading skill and vocabulary)</li>
<li>Report the model fit statistics overall (<span class="math inline">\(F, R^2\)</span>)</li>
<li>Report the significant effects (<span class="math inline">\(\beta, t, p\)</span>) and describe the nature of the effects (does the outcome increase or decrease?)</li>
</ol>
<blockquote class="blockquote">
<p>We fitted a linear model with mean comprehension accuracy as the outcome and vocabulary (Shipley) as the predictor. Our analysis indicated a significant effect of vocabulary knowledge. The model is significant overall, with <span class="math inline">\(F(1, 167) = 21.03, p &lt; .001\)</span>, and explains 11% of variance (<span class="math inline">\(\text{adjusted } R^2 = 0.11\)</span>). The model estimates showed that the accuracy of comprehension increased with increasing levels of participant vocabulary knowledge (<span class="math inline">\(\beta = .011, t = 4.59, p &lt;.001\)</span>).</p>
</blockquote>
</section>
</section>
<section id="summary" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="summary"><span class="header-section-number">5.7</span> Summary</h2>
<ul>
<li>In psychological science, we often ask questions like:</li>
</ul>
<ol type="1">
<li>Does variation in X predict variation in Y?</li>
<li>What are the factors that influence outcome Y?</li>
<li>Is a theoretical model consistent with observed behaviour?</li>
</ol>
<ul>
<li>We can answer these questions using the linear model</li>
<li>Given sample data, we can predict the average difference in outcome values, for different levels of a predictor variable</li>
<li>We (or the math engine R uses) calculate the predictions so that they minimize the residuals, the errors of prediction or the mismatch between predicted and observed outcomes</li>
<li>Our results report tells the reader about the model and the estimated effects</li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" data-line-spacing="2" role="list" style="display: none">
<div id="ref-freed2017" class="csl-entry" role="listitem">
Freed, E. M., Hamilton, S. T., &amp; Long, D. L. (2017). Comprehension in proficient readers: The nature of individual variation. <em>Journal of Memory and Language</em>, <em>97</em>, 135–153. <a href="https://doi.org/10.1016/j.jml.2017.07.008">https://doi.org/10.1016/j.jml.2017.07.008</a>
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
          // default icon
          link.classList.add("external");
      }
    }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./visualization.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data visualization</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./lm-dev.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Developing the linear model</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>